# Importar variables dando una "pista" del formato a Spring Boot
spring.config.import=optional:file:.env[.properties]

# Configuracion del Servidor
server.port=8080

# Configuracion de conexion a PostgreSQL usando Variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
